
import type { Cents } from "@/types/booking";

export type CatalogCategory = {
  id: string;
  name: string;
  examples: string[];
};

export type CatalogService = {
  id: string;
  categoryId: string;
  name: string;
  priceFrom: Cents;
  durationMinutes: number;
};

export const CATALOG_CATEGORIES: CatalogCategory[] = [
  {
    id: "appliance_repair",
    name: "Eletrodomésticos",
    examples: ["Geladeira", "Máquina de lavar", "Fogão", "Micro-ondas"],
  },
  {
    id: "electronics",
    name: "Eletrônicos e informática",
    examples: ["TV", "Notebook", "Celular", "Wi-Fi"],
  },
  {
    id: "renovation",
    name: "Reformas e reparos",
    examples: ["Pedreiro", "Pintor", "Gesseiro", "Montagem de móveis"],
  },
  {
    id: "electrical",
    name: "Elétrica",
    examples: ["Eletricista", "Tomada", "Chuveiro elétrico", "Disjuntor"],
  },
  {
    id: "plumbing",
    name: "Hidráulica",
    examples: ["Encanador", "Vazamento", "Desentupimento", "Caixa d'água"],
  },
  {
    id: "hvac",
    name: "Refrigeração e ar-condicionado",
    examples: ["Split", "Limpeza", "Instalação", "Recarga de gás"],
  },
  {
    id: "cleaning",
    name: "Limpeza",
    examples: ["Faxina", "Pós-obra", "Sofá", "Dedetização"],
  },
  {
    id: "beauty",
    name: "Beleza e estética",
    examples: ["Cabelo", "Unhas", "Sobrancelha", "Maquiagem"],
  },
  {
    id: "wellness",
    name: "Saúde e bem-estar",
    examples: ["Massagem", "Personal trainer", "Fisioterapia", "Nutrição"],
  },
  {
    id: "pet",
    name: "Pet",
    examples: ["Banho e tosa", "Passeio", "Veterinário", "Adestramento"],
  },
  {
    id: "lessons",
    name: "Aulas e reforço",
    examples: ["Reforço escolar", "Inglês", "Música", "Direção"],
  },
  {
    id: "automotive",
    name: "Automóveis",
    examples: ["Mecânico", "Lavagem", "Elétrica do carro", "Pneu"],
  },
  {
    id: "other",
    name: "Outros",
    examples: ["Serviço a combinar", "Por hora", "Ajudante"],
  },
];

export const CATALOG_SERVICES: CatalogService[] = [
  {
    id: "fridge_repair",
    categoryId: "appliance_repair",
    name: "Conserto de geladeira",
    priceFrom: 18000,
    durationMinutes: 90,
  },
  {
    id: "washer_repair",
    categoryId: "appliance_repair",
    name: "Conserto de máquina de lavar",
    priceFrom: 16000,
    durationMinutes: 90,
  },
  {
    id: "stove_repair",
    categoryId: "appliance_repair",
    name: "Conserto de fogão",
    priceFrom: 14000,
    durationMinutes: 60,
  },
  {
    id: "microwave_repair",
    categoryId: "appliance_repair",
    name: "Conserto de micro-ondas",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "dryer_repair",
    categoryId: "appliance_repair",
    name: "Conserto de secadora de roupas",
    priceFrom: 17000,
    durationMinutes: 90,
  },
  {
    id: "dishwasher_repair",
    categoryId: "appliance_repair",
    name: "Conserto de lava-louças",
    priceFrom: 18000,
    durationMinutes: 90,
  },
  {
    id: "tv_repair",
    categoryId: "electronics",
    name: "Conserto de TV",
    priceFrom: 15000,
    durationMinutes: 60,
  },
  {
    id: "tv_wall_mount",
    categoryId: "electronics",
    name: "Instalação de suporte de TV",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "notebook_repair",
    categoryId: "electronics",
    name: "Conserto de notebook",
    priceFrom: 15000,
    durationMinutes: 90,
  },
  {
    id: "phone_screen_repair",
    categoryId: "electronics",
    name: "Troca de tela de celular",
    priceFrom: 18000,
    durationMinutes: 60,
  },
  {
    id: "computer_setup",
    categoryId: "electronics",
    name: "Formatação de computador",
    priceFrom: 12000,
    durationMinutes: 120,
  },
  {
    id: "wifi_setup",
    categoryId: "electronics",
    name: "Instalação de rede Wi-Fi",
    priceFrom: 15000,
    durationMinutes: 90,
  },
  {
    id: "water_cooler_repair",
    categoryId: "appliance_repair",
    name: "Conserto de bebedouro",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "wall_painting",
    categoryId: "renovation",
    name: "Pintura de parede",
    priceFrom: 30000,
    durationMinutes: 480,
  },
  {
    id: "small_masonry",
    categoryId: "renovation",
    name: "Pequeno reparo de alvenaria",
    priceFrom: 20000,
    durationMinutes: 240,
  },
  {
    id: "floor_tiling",
    categoryId: "renovation",
    name: "Assentamento de piso",
    priceFrom: 35000,
    durationMinutes: 480,
  },
  {
    id: "wall_tiling",
    categoryId: "renovation",
    name: "Assentamento de azulejo",
    priceFrom: 35000,
    durationMinutes: 480,
  },
  {
    id: "grout_repair",
    categoryId: "renovation",
    name: "Rejunte de banheiro",
    priceFrom: 15000,
    durationMinutes: 180,
  },
  {
    id: "drywall_install",
    categoryId: "renovation",
    name: "Instalação de drywall",
    priceFrom: 30000,
    durationMinutes: 480,
  },
  {
    id: "plaster_ceiling",
    categoryId: "renovation",
    name: "Forro de gesso",
    priceFrom: 30000,
    durationMinutes: 480,
  },
  {
    id: "crown_molding",
    categoryId: "renovation",
    name: "Instalação de moldura de gesso",
    priceFrom: 18000,
    durationMinutes: 240,
  },
  {
    id: "door_install",
    categoryId: "renovation",
    name: "Instalação de porta",
    priceFrom: 18000,
    durationMinutes: 180,
  },
  {
    id: "window_install",
    categoryId: "renovation",
    name: "Instalação de janela",
    priceFrom: 22000,
    durationMinutes: 240,
  },
  {
    id: "shelf_mounting",
    categoryId: "renovation",
    name: "Instalação de prateleira",
    priceFrom: 9000,
    durationMinutes: 60,
  },
  {
    id: "furniture_assembly",
    categoryId: "renovation",
    name: "Montagem de móveis",
    priceFrom: 12000,
    durationMinutes: 120,
  },
  {
    id: "roof_repair",
    categoryId: "renovation",
    name: "Conserto de telhado",
    priceFrom: 25000,
    durationMinutes: 240,
  },
  {
    id: "waterproofing",
    categoryId: "renovation",
    name: "Impermeabilização de laje",
    priceFrom: 40000,
    durationMinutes: 480,
  },
  {
    id: "outlet_install",
    categoryId: "electrical",
    name: "Instalação de tomada",
    priceFrom: 9000,
    durationMinutes: 60,
  },
  {
    id: "switch_replacement",
    categoryId: "electrical",
    name: "Troca de interruptor",
    priceFrom: 8000,
    durationMinutes: 45,
  },
  {
    id: "light_fixture_install",
    categoryId: "electrical",
    name: "Instalação de luminária",
    priceFrom: 10000,
    durationMinutes: 60,
  },
  {
    id: "led_replacement",
    categoryId: "electrical",
    name: "Troca de lâmpadas por LED",
    priceFrom: 8000,
    durationMinutes: 60,
  },
  {
    id: "ceiling_fan_install",
    categoryId: "electrical",
    name: "Instalação de ventilador de teto",
    priceFrom: 15000,
    durationMinutes: 90,
  },
  {
    id: "electric_shower_install",
    categoryId: "electrical",
    name: "Instalação de chuveiro elétrico",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "short_circuit_fix",
    categoryId: "electrical",
    name: "Conserto de curto-circuito",
    priceFrom: 15000,
    durationMinutes: 120,
  },
  {
    id: "breaker_panel_replacement",
    categoryId: "electrical",
    name: "Troca de quadro de disjuntores",
    priceFrom: 35000,
    durationMinutes: 240,
  },
  {
    id: "wiring_replacement",
    categoryId: "electrical",
    name: "Troca de fiação",
    priceFrom: 30000,
    durationMinutes: 480,
  },
  {
    id: "grounding_install",
    categoryId: "electrical",
    name: "Instalação de aterramento",
    priceFrom: 25000,
    durationMinutes: 180,
  },
  {
    id: "ac_power_point",
    categoryId: "electrical",
    name: "Ponto de força para ar-condicionado",
    priceFrom: 20000,
    durationMinutes: 180,
  },
  {
    id: "intercom_install",
    categoryId: "electrical",
    name: "Instalação de interfone",
    priceFrom: 18000,
    durationMinutes: 120,
  },
  {
    id: "electric_gate_repair",
    categoryId: "electrical",
    name: "Conserto de portão eletrônico",
    priceFrom: 20000,
    durationMinutes: 120,
  },
  {
    id: "leak_repair",
    categoryId: "plumbing",
    name: "Conserto de vazamento",
    priceFrom: 15000,
    durationMinutes: 120,
  },
  {
    id: "leak_detection",
    categoryId: "plumbing",
    name: "Caça-vazamento",
    priceFrom: 25000,
    durationMinutes: 120,
  },
  {
    id: "sink_unclogging",
    categoryId: "plumbing",
    name: "Desentupimento de pia",
    priceFrom: 15000,
    durationMinutes: 60,
  },
  {
    id: "toilet_unclogging",
    categoryId: "plumbing",
    name: "Desentupimento de vaso sanitário",
    priceFrom: 18000,
    durationMinutes: 60,
  },
  {
    id: "faucet_install",
    categoryId: "plumbing",
    name: "Instalação de torneira",
    priceFrom: 9000,
    durationMinutes: 45,
  },
  {
    id: "shower_install",
    categoryId: "plumbing",
    name: "Instalação de chuveiro",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "toilet_install",
    categoryId: "plumbing",
    name: "Instalação de vaso sanitário",
    priceFrom: 20000,
    durationMinutes: 120,
  },
  {
    id: "sink_install",
    categoryId: "plumbing",
    name: "Instalação de pia",
    priceFrom: 18000,
    durationMinutes: 120,
  },
  {
    id: "washer_hookup",
    categoryId: "plumbing",
    name: "Instalação de máquina de lavar",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "water_tank_cleaning",
    categoryId: "plumbing",
    name: "Limpeza de caixa d'água",
    priceFrom: 20000,
    durationMinutes: 120,
  },
  {
    id: "water_pump_install",
    categoryId: "plumbing",
    name: "Instalação de bomba d'água",
    priceFrom: 25000,
    durationMinutes: 180,
  },
  {
    id: "gas_heater_install",
    categoryId: "plumbing",
    name: "Instalação de aquecedor a gás",
    priceFrom: 30000,
    durationMinutes: 240,
  },
  {
    id: "gas_line_install",
    categoryId: "plumbing",
    name: "Instalação de ponto de gás",
    priceFrom: 25000,
    durationMinutes: 180,
  },
  {
    id: "split_ac_cleaning",
    categoryId: "hvac",
    name: "Limpeza de ar-condicionado split",
    priceFrom: 15000,
    durationMinutes: 90,
  },
  {
    id: "split_ac_install",
    categoryId: "hvac",
    name: "Instalação de ar-condicionado split",
    priceFrom: 45000,
    durationMinutes: 240,
  },
  {
    id: "split_ac_removal",
    categoryId: "hvac",
    name: "Desinstalação de ar-condicionado split",
    priceFrom: 25000,
    durationMinutes: 120,
  },
  {
    id: "split_ac_relocation",
    categoryId: "hvac",
    name: "Mudança de lugar do ar-condicionado",
    priceFrom: 40000,
    durationMinutes: 240,
  },
  {
    id: "ac_gas_recharge",
    categoryId: "hvac",
    name: "Recarga de gás do ar-condicionado",
    priceFrom: 30000,
    durationMinutes: 120,
  },
  {
    id: "ac_repair",
    categoryId: "hvac",
    name: "Conserto de ar-condicionado",
    priceFrom: 20000,
    durationMinutes: 120,
  },
  {
    id: "ac_preventive_maintenance",
    categoryId: "hvac",
    name: "Manutenção preventiva de ar-condicionado",
    priceFrom: 18000,
    durationMinutes: 90,
  },
  {
    id: "window_ac_cleaning",
    categoryId: "hvac",
    name: "Limpeza de ar-condicionado de janela",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "freezer_repair",
    categoryId: "hvac",
    name: "Conserto de freezer",
    priceFrom: 18000,
    durationMinutes: 90,
  },
  {
    id: "display_cooler_repair",
    categoryId: "hvac",
    name: "Conserto de expositor refrigerado",
    priceFrom: 25000,
    durationMinutes: 120,
  },
  {
    id: "cold_room_maintenance",
    categoryId: "hvac",
    name: "Manutenção de câmara fria",
    priceFrom: 35000,
    durationMinutes: 180,
  },
  {
    id: "ice_machine_repair",
    categoryId: "hvac",
    name: "Conserto de máquina de gelo",
    priceFrom: 25000,
    durationMinutes: 120,
  },
  {
    id: "fountain_sanitizing",
    categoryId: "hvac",
    name: "Higienização de bebedouro",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "house_cleaning",
    categoryId: "cleaning",
    name: "Faxina completa",
    priceFrom: 18000,
    durationMinutes: 360,
  },
  {
    id: "deep_cleaning",
    categoryId: "cleaning",
    name: "Limpeza pesada",
    priceFrom: 25000,
    durationMinutes: 480,
  },
  {
    id: "post_construction_cleaning",
    categoryId: "cleaning",
    name: "Limpeza pós-obra",
    priceFrom: 30000,
    durationMinutes: 480,
  },
  {
    id: "office_cleaning",
    categoryId: "cleaning",
    name: "Limpeza de escritório",
    priceFrom: 20000,
    durationMinutes: 300,
  },
  {
    id: "window_cleaning",
    categoryId: "cleaning",
    name: "Limpeza de vidros",
    priceFrom: 15000,
    durationMinutes: 180,
  },
  {
    id: "sofa_sanitizing",
    categoryId: "cleaning",
    name: "Higienização de sofá",
    priceFrom: 15000,
    durationMinutes: 120,
  },
  {
    id: "mattress_sanitizing",
    categoryId: "cleaning",
    name: "Higienização de colchão",
    priceFrom: 12000,
    durationMinutes: 90,
  },
  {
    id: "rug_cleaning",
    categoryId: "cleaning",
    name: "Limpeza de tapete",
    priceFrom: 12000,
    durationMinutes: 90,
  },
  {
    id: "kitchen_degreasing",
    categoryId: "cleaning",
    name: "Desengorduramento de cozinha",
    priceFrom: 18000,
    durationMinutes: 180,
  },
  {
    id: "ironing",
    categoryId: "cleaning",
    name: "Passar roupa",
    priceFrom: 12000,
    durationMinutes: 240,
  },
  {
    id: "facade_washing",
    categoryId: "cleaning",
    name: "Lavagem de fachada",
    priceFrom: 30000,
    durationMinutes: 300,
  },
  {
    id: "pool_cleaning",
    categoryId: "cleaning",
    name: "Limpeza de piscina",
    priceFrom: 20000,
    durationMinutes: 120,
  },
  {
    id: "yard_cleanup",
    categoryId: "cleaning",
    name: "Limpeza de quintal",
    priceFrom: 15000,
    durationMinutes: 180,
  },
  {
    id: "pest_control",
    categoryId: "cleaning",
    name: "Dedetização",
    priceFrom: 20000,
    durationMinutes: 120,
  },
  {
    id: "women_haircut",
    categoryId: "beauty",
    name: "Corte de cabelo feminino",
    priceFrom: 6000,
    durationMinutes: 60,
  },
  {
    id: "men_haircut",
    categoryId: "beauty",
    name: "Corte de cabelo masculino",
    priceFrom: 4000,
    durationMinutes: 45,
  },
  {
    id: "beard_trim",
    categoryId: "beauty",
    name: "Barba",
    priceFrom: 3000,
    durationMinutes: 30,
  },
  {
    id: "blow_dry",
    categoryId: "beauty",
    name: "Escova",
    priceFrom: 5000,
    durationMinutes: 60,
  },
  {
    id: "hair_coloring",
    categoryId: "beauty",
    name: "Coloração",
    priceFrom: 15000,
    durationMinutes: 180,
  },
  {
    id: "hair_highlights",
    categoryId: "beauty",
    name: "Mechas",
    priceFrom: 25000,
    durationMinutes: 240,
  },
  {
    id: "hair_straightening",
    categoryId: "beauty",
    name: "Progressiva",
    priceFrom: 20000,
    durationMinutes: 180,
  },
  {
    id: "manicure",
    categoryId: "beauty",
    name: "Manicure",
    priceFrom: 3500,
    durationMinutes: 60,
  },
  {
    id: "pedicure",
    categoryId: "beauty",
    name: "Pedicure",
    priceFrom: 4000,
    durationMinutes: 60,
  },
  {
    id: "nail_extension",
    categoryId: "beauty",
    name: "Alongamento de unhas",
    priceFrom: 12000,
    durationMinutes: 150,
  },
  {
    id: "eyebrow_design",
    categoryId: "beauty",
    name: "Design de sobrancelha",
    priceFrom: 4000,
    durationMinutes: 30,
  },
  {
    id: "eyelash_extension",
    categoryId: "beauty",
    name: "Extensão de cílios",
    priceFrom: 12000,
    durationMinutes: 120,
  },
  {
    id: "makeup",
    categoryId: "beauty",
    name: "Maquiagem",
    priceFrom: 12000,
    durationMinutes: 90,
  },
  {
    id: "waxing",
    categoryId: "beauty",
    name: "Depilação",
    priceFrom: 5000,
    durationMinutes: 45,
  },
  {
    id: "relaxing_massage",
    categoryId: "wellness",
    name: "Massagem relaxante",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "modeling_massage",
    categoryId: "wellness",
    name: "Massagem modeladora",
    priceFrom: 15000,
    durationMinutes: 60,
  },
  {
    id: "lymphatic_drainage",
    categoryId: "wellness",
    name: "Drenagem linfática",
    priceFrom: 13000,
    durationMinutes: 60,
  },
  {
    id: "skin_cleansing",
    categoryId: "wellness",
    name: "Limpeza de pele",
    priceFrom: 12000,
    durationMinutes: 90,
  },
  {
    id: "personal_trainer",
    categoryId: "wellness",
    name: "Personal trainer",
    priceFrom: 8000,
    durationMinutes: 60,
  },
  {
    id: "pilates_class",
    categoryId: "wellness",
    name: "Aula de pilates",
    priceFrom: 8000,
    durationMinutes: 60,
  },
  {
    id: "yoga_class",
    categoryId: "wellness",
    name: "Aula de yoga",
    priceFrom: 8000,
    durationMinutes: 60,
  },
  {
    id: "nutrition_consult",
    categoryId: "wellness",
    name: "Consulta com nutricionista",
    priceFrom: 15000,
    durationMinutes: 60,
  },
  {
    id: "physiotherapy_session",
    categoryId: "wellness",
    name: "Sessão de fisioterapia",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "acupuncture_session",
    categoryId: "wellness",
    name: "Sessão de acupuntura",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "podiatry",
    categoryId: "wellness",
    name: "Podologia",
    priceFrom: 8000,
    durationMinutes: 60,
  },
  {
    id: "speech_therapy",
    categoryId: "wellness",
    name: "Sessão de fonoaudiologia",
    priceFrom: 12000,
    durationMinutes: 45,
  },
  {
    id: "home_nursing",
    categoryId: "wellness",
    name: "Cuidados de enfermagem em casa",
    priceFrom: 15000,
    durationMinutes: 120,
  },
  {
    id: "elderly_companion",
    categoryId: "wellness",
    name: "Acompanhante de idosos",
    priceFrom: 15000,
    durationMinutes: 240,
  },
  {
    id: "dog_bath",
    categoryId: "pet",
    name: "Banho em cachorro",
    priceFrom: 5000,
    durationMinutes: 60,
  },
  {
    id: "dog_bath_and_grooming",
    categoryId: "pet",
    name: "Banho e tosa",
    priceFrom: 8000,
    durationMinutes: 90,
  },
  {
    id: "hygienic_grooming",
    categoryId: "pet",
    name: "Tosa higiênica",
    priceFrom: 5000,
    durationMinutes: 45,
  },
  {
    id: "scissor_grooming",
    categoryId: "pet",
    name: "Tosa na tesoura",
    priceFrom: 10000,
    durationMinutes: 120,
  },
  {
    id: "cat_bath",
    categoryId: "pet",
    name: "Banho em gato",
    priceFrom: 7000,
    durationMinutes: 60,
  },
  {
    id: "pet_nail_trim",
    categoryId: "pet",
    name: "Corte de unhas do pet",
    priceFrom: 2500,
    durationMinutes: 30,
  },
  {
    id: "pet_teeth_brushing",
    categoryId: "pet",
    name: "Escovação de dentes do pet",
    priceFrom: 3000,
    durationMinutes: 30,
  },
  {
    id: "dog_walking",
    categoryId: "pet",
    name: "Passeio com cachorro",
    priceFrom: 3000,
    durationMinutes: 60,
  },
  {
    id: "pet_sitter",
    categoryId: "pet",
    name: "Pet sitter em casa",
    priceFrom: 5000,
    durationMinutes: 60,
  },
  {
    id: "dog_training",
    categoryId: "pet",
    name: "Adestramento",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "vet_home_visit",
    categoryId: "pet",
    name: "Consulta veterinária em casa",
    priceFrom: 18000,
    durationMinutes: 60,
  },
  {
    id: "pet_vaccination",
    categoryId: "pet",
    name: "Vacinação do pet",
    priceFrom: 9000,
    durationMinutes: 30,
  },
  {
    id: "pet_taxi",
    categoryId: "pet",
    name: "Táxi pet",
    priceFrom: 6000,
    durationMinutes: 60,
  },
  {
    id: "math_tutoring",
    categoryId: "lessons",
    name: "Reforço de matemática",
    priceFrom: 6000,
    durationMinutes: 60,
  },
  {
    id: "portuguese_tutoring",
    categoryId: "lessons",
    name: "Reforço de português",
    priceFrom: 6000,
    durationMinutes: 60,
  },
  {
    id: "homework_support",
    categoryId: "lessons",
    name: "Acompanhamento de lição de casa",
    priceFrom: 5000,
    durationMinutes: 60,
  },
  {
    id: "enem_prep",
    categoryId: "lessons",
    name: "Preparatório para o Enem",
    priceFrom: 8000,
    durationMinutes: 90,
  },
  {
    id: "english_lesson",
    categoryId: "lessons",
    name: "Aula de inglês",
    priceFrom: 7000,
    durationMinutes: 60,
  },
  {
    id: "spanish_lesson",
    categoryId: "lessons",
    name: "Aula de espanhol",
    priceFrom: 6500,
    durationMinutes: 60,
  },
  {
    id: "guitar_lesson",
    categoryId: "lessons",
    name: "Aula de violão",
    priceFrom: 6000,
    durationMinutes: 60,
  },
  {
    id: "piano_lesson",
    categoryId: "lessons",
    name: "Aula de piano",
    priceFrom: 8000,
    durationMinutes: 60,
  },
  {
    id: "singing_lesson",
    categoryId: "lessons",
    name: "Aula de canto",
    priceFrom: 8000,
    durationMinutes: 60,
  },
  {
    id: "dance_lesson",
    categoryId: "lessons",
    name: "Aula de dança",
    priceFrom: 7000,
    durationMinutes: 60,
  },
  {
    id: "swimming_lesson",
    categoryId: "lessons",
    name: "Aula de natação",
    priceFrom: 8000,
    durationMinutes: 45,
  },
  {
    id: "driving_lesson",
    categoryId: "lessons",
    name: "Aula de direção",
    priceFrom: 10000,
    durationMinutes: 60,
  },
  {
    id: "computer_lesson",
    categoryId: "lessons",
    name: "Aula de informática",
    priceFrom: 6000,
    durationMinutes: 60,
  },
  {
    id: "programming_lesson",
    categoryId: "lessons",
    name: "Aula de programação",
    priceFrom: 10000,
    durationMinutes: 60,
  },
  {
    id: "oil_change",
    categoryId: "automotive",
    name: "Troca de óleo",
    priceFrom: 15000,
    durationMinutes: 60,
  },
  {
    id: "car_wash",
    categoryId: "automotive",
    name: "Lavagem completa",
    priceFrom: 8000,
    durationMinutes: 90,
  },
  {
    id: "car_polishing",
    categoryId: "automotive",
    name: "Polimento",
    priceFrom: 30000,
    durationMinutes: 240,
  },
  {
    id: "car_upholstery_cleaning",
    categoryId: "automotive",
    name: "Higienização de estofados do carro",
    priceFrom: 20000,
    durationMinutes: 180,
  },
  {
    id: "brake_pad_replacement",
    categoryId: "automotive",
    name: "Troca de pastilha de freio",
    priceFrom: 18000,
    durationMinutes: 120,
  },
  {
    id: "battery_replacement",
    categoryId: "automotive",
    name: "Troca de bateria",
    priceFrom: 10000,
    durationMinutes: 30,
  },
  {
    id: "tire_change",
    categoryId: "automotive",
    name: "Troca de pneu",
    priceFrom: 6000,
    durationMinutes: 45,
  },
  {
    id: "wheel_alignment",
    categoryId: "automotive",
    name: "Alinhamento e balanceamento",
    priceFrom: 12000,
    durationMinutes: 60,
  },
  {
    id: "suspension_repair",
    categoryId: "automotive",
    name: "Conserto de suspensão",
    priceFrom: 25000,
    durationMinutes: 180,
  },
  {
    id: "car_electrical_check",
    categoryId: "automotive",
    name: "Revisão elétrica do carro",
    priceFrom: 15000,
    durationMinutes: 90,
  },
  {
    id: "car_ac_recharge",
    categoryId: "automotive",
    name: "Recarga do ar-condicionado do carro",
    priceFrom: 25000,
    durationMinutes: 90,
  },
  {
    id: "paintless_dent_repair",
    categoryId: "automotive",
    name: "Martelinho de ouro",
    priceFrom: 25000,
    durationMinutes: 180,
  },
  {
    id: "window_tinting",
    categoryId: "automotive",
    name: "Aplicação de película",
    priceFrom: 30000,
    durationMinutes: 180,
  },
  {
    id: "custom_service",
    categoryId: "other",
    name: "Serviço a combinar",
    priceFrom: 10000,
    durationMinutes: 60,
  },
  {
    id: "hourly_help",
    categoryId: "other",
    name: "Ajudante por hora",
    priceFrom: 8000,
    durationMinutes: 60,
  },
];

const CUSTOM_PREFIX = "custom:";

export function customCatalogId(categoryId: string) {
  return `${CUSTOM_PREFIX}${categoryId}:${Math.random().toString(36).slice(2, 8)}`;
}

export function isCustomCatalogId(catalogId: string) {
  return catalogId.startsWith(CUSTOM_PREFIX);
}

export function categoryOf(catalogId: string): string | null {
  if (isCustomCatalogId(catalogId)) {
    return catalogId.slice(CUSTOM_PREFIX.length).split(":")[0] || null;
  }

  return (
    CATALOG_SERVICES.find((item) => item.id === catalogId)?.categoryId ?? null
  );
}

export function tradesOf(
  services: ReadonlyArray<{ catalogId: string }>,
  limit = 3,
): string[] {
  const found = new Set<string>();
  for (const service of services) {
    const category = categoryOf(service.catalogId);
    if (category) found.add(category);
  }

  return CATALOG_CATEGORIES.filter((category) => found.has(category.id))
    .slice(0, limit)
    .map((category) => category.name);
}

export function countByCategory(
  services: ReadonlyArray<{ catalogId: string }>,
): Record<string, number> {
  const count: Record<string, number> = {};

  for (const service of services) {
    const category = categoryOf(service.catalogId);
    if (!category) continue;
    count[category] = (count[category] ?? 0) + 1;
  }

  return count;
}
